#!/usr/bin / env node
/* eslint-disable @typescript-eslint/no-var-requires */
const concourseResource = require('../dist/bin/index');
// pass the actual argv which are starting from the index 2
concourseResource.execOut([...process.argv].slice(2));
